language: java
install: true


dist: trusty
jdk:
  - openjdk13
  - openjdk-ea


matrix:
  allow_failures:
    - jdk: openjdk-ea

branches:
  only:
  - master
  - v7.6.0

script:
  - export JAVA8_HOME=$OPENJDK8_JAVA_HOME
  - export JAVA11_HOME=$OPENJDK11_JAVA_HOME
  - ./gradlew --continue clean build --scan -s -p modules/