language: java
install: true


dist: trusty
jdk:
  - openjdk13


branches:
  only:
  - master
  - v7.6.0

script:
  - export JAVA8_HOME=$OPENJDK8_JAVA_HOME
  - export JAVA11_HOME=$OPENJDK11_JAVA_HOME
  - export JAVA12_HOME=~/openjdk12
  - export JAVA13_HOME=$JAVA_HOME
  - ~/bin/install-jdk.sh  --target $JAVA12_HOME --feature "12" --license "GPL"
  - ./gradlew --continue clean build --scan -s -p modules/